dist: trusty
sudo: required

script:
  - curl -O https://raw.githubusercontent.com/kylepjohnson/python3_bootstrap/master/install.sh
  - chmod +x install.sh
  - ./install.sh 3
  - python3.7 -m venv venv3
  - source venv3/bin/activate
  - python --version
  - deactivate

#  - ./install.sh 2
#  - virtualenv venv2
#  - source venv2/bin/activate
#  - python --version
#  - /usr/local/bin/virtualenv venv2
#  - source venv2/bin/activate
#  - python --version
#  - deactivate
