script:
  - curl -O https://raw.githubusercontent.com/kylepjohnson/python3_bootstrap/master/install.sh
  - chmod +x install.sh
  - ./install.sh no-update
  - pyvenv venv
  - source venv/bin/activate
  - python --version
