dist: trusty
sudo: required

script:
  - curl -O https://raw.githubusercontent.com/kylepjohnson/python3_bootstrap/master/install.sh
  - chmod +x install.sh
  - ./install.sh 3
  - python3.6 -m venv venv
  - source venv3/bin/activate
  - python --version
